server:
  port: 12345
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydata?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 1q2w3e4r
#??url??????????????????????????????????

#mysql??????gbk????????????utf-8???????????useUnicode=true&characterEncoding=UTF-8
#?????
#????????????????UTF-8???????????????????????????GBK??????????
#?????
#???????????????????????????GBK???????????????????????UTF-8????????????????????
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以不加步骤2的注解)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

